# Shared 25-method test set for the R4 studies.
TASKS = [
 ("Math-2 getNumericalMean", ["public double getNumericalMean()","public int sample()","public double cumulativeProbability(int x)"], ["public double getNumericalMean()"],
  "getNumericalMean HypergeometricDistribution the mean of the distribution n*m/N cumulative probability sample"),
 ("Math-53 Complex.add", ["public Complex add(Complex addend)"], ["public Complex add(Complex addend)"],
  "add Complex returns a Complex whose value is this plus the addend real imaginary NaN"),
 ("Math-57 KMeans assignPoints", ["private int assignPointsToClusters(List clusters, Collection points)"], ["private int assignPointsToClusters(List clusters, Collection points)"],
  "assignPointsToClusters KMeansPlusPlusClusterer nearest cluster distance points list"),
 ("Lang-7 createNumber", ["public static Number createNumber(String str)"], ["public static Number createNumber(String str)"],
  "createNumber NumberUtils turns a string into a java.lang.Number hex float"),
 ("Lang-41 getPackageName", ["public static String getPackageName(Class cls)","public static String getPackageName(String className)"], ["public static String getPackageName(Class cls)","public static String getPackageName(String className)"],
  "getPackageName getShortClassName ClassUtils the package name of a class"),
 ("Lang-60 StrBuilder.contains", ["public boolean contains(char ch)","public StrBuilder deleteFirst(String str)","public int indexOf(char ch)"], ["public boolean contains(char ch)"],
  "contains char whether the builder contains a character StrBuilder capacity length indexOf deleteFirst"),
 ("Time-4 Partial.with", ["public Partial with(DateTimeFieldType fieldType, int value)"], ["public Partial with(DateTimeFieldType fieldType, int value)"],
  "Partial with DateTimeFieldType value the partial datetime chronology field instant"),
 ("Time-11 DateTimeZone.forID", ["public static DateTimeZone forID(String id)"], ["public static DateTimeZone forID(String id)"],
  "forID DateTimeZone gets a time zone instance for the specified id offset"),
 ("Closure-62 formatError", ["public String formatError(JSError error)","LightweightMessageFormatter formatter(String sourceCode)"], ["public String formatError(JSError error)"],
  "formatError JSError LightweightMessageFormatter formats an error against the source code line"),
 ("Closure-33 matchConstraint", ["public void matchConstraint(ObjectType constraint)"], ["public void matchConstraint(ObjectType constraint)"],
  "matchConstraint ObjectType PrototypeObjectType infer property record type"),
 ("Chart-26 CategoryPlot.draw", ["public void draw(Graphics2D g2, Rectangle2D area, Point2D anchor, ChartRenderingInfo info)"], ["public void draw(Graphics2D g2, Rectangle2D area, Point2D anchor, ChartRenderingInfo info)"],
  "draw CategoryPlot renders the plot within the given area axis entity bounds rectangle"),
 ("Chart-1 Range.combine", ["public static Range combine(Range range1, Range range2)","public double getLength()"], ["public static Range combine(Range range1, Range range2)"],
  "combine Range creates a new range by combining two ranges lower upper null length"),
 ("Chart-7 TimeSeries.getMaxY", ["public double getMaxY()","public void add(TimePeriod period, double value)"], ["public double getMaxY()"],
  "getMaxY TimeSeries the maximum y-value in the series bounds range add item"),
 ("Math-70 BisectionSolver.solve", ["public double solve(UnivariateFunction f, double min, double max)"], ["public double solve(UnivariateFunction f, double min, double max)"],
  "solve BisectionSolver find a root of the function between min and max iterations tolerance converge"),
 # --- standard library spread ---
 ("String.split", ["public String[] split(String regex)"], ["public String[] split(String regex)"],
  "split String splits this string around matches of the given regular expression trailing empty"),
 ("Collections.sort", ["public static void sort(List list)"], ["public static void sort(List list)"],
  "sort Collections sorts the specified list into ascending order stable comparator"),
 ("String.replace", ["public String replace(CharSequence target, CharSequence replacement)"], ["public String replace(CharSequence target, CharSequence replacement)"],
  "replace String replaces each substring that matches the target sequence count length"),
 ("LocalDate.plusDays", ["public LocalDate plusDays(long days)"], ["public LocalDate plusDays(long days)"],
  "plusDays LocalDate returns a copy of this date with the specified days added duration period"),
 ("Rectangle2D.createUnion", ["public Rectangle2D createUnion(Rectangle2D r)"], ["public Rectangle2D createUnion(Rectangle2D r)"],
  "createUnion Rectangle2D the smallest rectangle containing both this and the specified rectangle bounds"),
 ("Base64.encode", ["public byte[] encode(byte[] src)","public byte[] decode(byte[] src)"], ["public byte[] encode(byte[] src)"],
  "encode Base64 encodes the specified byte array decode roundtrip"),
 ("StringUtils.reverse", ["public static String reverse(String str)"], ["public static String reverse(String str)"],
  "reverse StringUtils reverses a string surrogate code point"),
 ("BigDecimal.add", ["public BigDecimal add(BigDecimal augend)"], ["public BigDecimal add(BigDecimal augend)"],
  "add BigDecimal returns a BigDecimal whose value is this plus augend scale precision"),
 ("TreeMap.put", ["public Object put(Object key, Object value)"], ["public Object put(Object key, Object value)"],
  "put TreeMap associates the specified value with the specified key size contains order"),
 ("ArrayUtils.indexOf", ["public static int indexOf(Object[] array, Object obj)"], ["public static int indexOf(Object[] array, Object obj)"],
  "indexOf ArrayUtils finds the index of the given object in the array search contains"),
 ("MessageDigest.digest", ["public byte[] digest(byte[] input)"], ["public byte[] digest(byte[] input)"],
  "digest MessageDigest performs a final update and computes the hash value bytes"),
]
