"""Extract and compile a C harness generated by the LLM.

Supports two harness styles:
  'syscall'   — compiled with gcc, no special flags. Binary run directly.
  'libfuzzer' — compiled with clang -fsanitize=address,fuzzer.
                Requires a kernel checkout for include paths.

Analogous to src/java/build.py but for C.
"""
import os
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

sys.path.insert(0, str(Path(__file__).parent.parent))
import config


@dataclass
class LinuxBuildResult:
    success: bool
    binary_path: Optional[str]     # path to compiled binary (None on failure)
    source_path: Optional[str]     # path to extracted .c file
    compiler_stderr: str           # full compiler output for repair turns
    attempt_label: str


def _extract_c_source(llm_response: str) -> Optional[str]:
    """Extract the first ```c ... ``` block from the LLM response."""
    m = re.search(r"```c\s*\n(.*?)```", llm_response, re.DOTALL)
    if m:
        return m.group(1)
    # Fallback: try a plain ``` block.
    m = re.search(r"```\s*\n(.*?)```", llm_response, re.DOTALL)
    return m.group(1) if m else None


def build(
    llm_response: str,
    attempt_label: str,
    harness_style: str = "syscall",
    kernel_checkout: Optional[str] = None,
    output_dir: Optional[str] = None,
) -> LinuxBuildResult:
    """Extract C source from LLM response and compile it.

    Args:
        llm_response:     Raw LLM text containing a ```c ... ``` block.
        attempt_label:    Short label used to name output files (e.g. 'attempt_003').
        harness_style:    'syscall' or 'libfuzzer'.
        kernel_checkout:  Path to a kernel worktree (required for libfuzzer style).
        output_dir:       Where to write the .c and binary. Defaults to a tempdir.
    """
    source = _extract_c_source(llm_response)
    if source is None:
        return LinuxBuildResult(
            success=False,
            binary_path=None,
            source_path=None,
            compiler_stderr="No ```c ... ``` block found in LLM response.",
            attempt_label=attempt_label,
        )

    out_dir = Path(output_dir) if output_dir else Path(tempfile.mkdtemp(prefix="vuln_patch_linux_"))
    out_dir.mkdir(parents=True, exist_ok=True)

    src_path = out_dir / f"{attempt_label}.c"
    bin_path = out_dir / attempt_label
    src_path.write_text(source)

    cmd = _build_command(harness_style, src_path, bin_path, kernel_checkout)
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=60,
        )
        success = result.returncode == 0 and bin_path.exists()
        return LinuxBuildResult(
            success=success,
            binary_path=str(bin_path) if success else None,
            source_path=str(src_path),
            compiler_stderr=(result.stdout + result.stderr).strip(),
            attempt_label=attempt_label,
        )
    except subprocess.TimeoutExpired:
        return LinuxBuildResult(
            success=False,
            binary_path=None,
            source_path=str(src_path),
            compiler_stderr="Compilation timed out after 60 seconds.",
            attempt_label=attempt_label,
        )
    except FileNotFoundError as e:
        return LinuxBuildResult(
            success=False,
            binary_path=None,
            source_path=str(src_path),
            compiler_stderr=f"Compiler not found: {e}",
            attempt_label=attempt_label,
        )


def _build_command(
    style: str,
    src: Path,
    out: Path,
    kernel_checkout: Optional[str],
) -> list[str]:
    if style == "libfuzzer":
        includes = _kernel_includes(kernel_checkout)
        return [
            "clang",
            "-fsanitize=address,fuzzer",
            "-g", "-O1",
            *includes,
            str(src), "-o", str(out),
        ]
    else:
        # syscall-sequence: plain gcc, minimal flags
        return [
            "gcc",
            "-g", "-O0",
            "-Wall", "-Wno-unused-variable",
            str(src), "-o", str(out),
            "-lpthread",
        ]


def _kernel_includes(kernel_checkout: Optional[str]) -> list[str]:
    if not kernel_checkout:
        return []
    base = Path(kernel_checkout)
    paths = [
        base / "include",
        base / "arch" / "x86" / "include",
        base / "arch" / "x86" / "include" / "generated",
    ]
    return [f"-I{p}" for p in paths if p.exists()]
